services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./src:/app
    container_name: yii2-app
    restart: always
    networks:
      - app_network
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    build:
      context: ./docker/nginx
    container_name: yii2-nginx
    ports:
      - "${APP_PORT}:80"
    networks:
      - app_network
    volumes:
      - ./src:/app
    depends_on:
      - php

  db:
    image: postgres:15
    container_name: yii2-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '54322:5432'
    networks:
      - app_network
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  app_network:
